services:
  exporter:
    image: payt-nginx-exporter
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exporter
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:ro
      - ./config.json:/app/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: ${HOSTNAME}
    # network_mode: host
    networks:
      - web

networks:
  web:
    external: true