services:
  exporter:
    image: payt-nginx-exporter
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exporter
    restart: always
    volumes:
      - ./:/app:ro
      - ./config.json:/app/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: ${HOSTNAME}
    network_mode: host